import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import {
  Outlet,
  Link,
  createRootRouteWithContext,
  useRouter,
  useRouterState,
  HeadContent,
  Scripts,
} from "@tanstack/react-router";
import { useEffect } from "react";
import { reportCallConversion } from "@/lib/track";
import { HOTJAR_BOOTSTRAP, TRACKING_BOOTSTRAP } from "@/lib/tracking-bootstrap";

import appCss from "../styles.css?url";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
// ScheduleWidget popup removed — scheduling lives on /schedule.
// TimedLeadPopup removed — no pop-ups per product direction.
import { StickyMobileCta } from "@/components/StickyMobileCta";
import { Toaster } from "@/components/ui/sonner";

function NotFoundComponent() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-7xl font-bold text-foreground">404</h1>
        <h2 className="mt-4 text-xl font-semibold text-foreground">Page not found</h2>
        <p className="mt-2 text-sm text-muted-foreground">
          The page you're looking for doesn't exist or has been moved.
        </p>
        <div className="mt-6">
          <Link
            to="/"
            className="inline-flex items-center justify-center rounded-none bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Go home
          </Link>
        </div>
      </div>
    </div>
  );
}

function ErrorComponent({ error, reset }: { error: Error; reset: () => void }) {
  console.error(error);
  const router = useRouter();

  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-xl font-semibold tracking-tight text-foreground">
          This page didn't load
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Something went wrong on our end. You can try refreshing or head back home.
        </p>
        <div className="mt-6 flex flex-wrap justify-center gap-2">
          <button
            onClick={() => {
              router.invalidate();
              reset();
            }}
            className="inline-flex items-center justify-center rounded-none bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Try again
          </button>
          <a
            href="/"
            className="inline-flex items-center justify-center rounded-none border border-input bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent"
          >
            Go home
          </a>
        </div>
      </div>
    </div>
  );
}

export const Route = createRootRouteWithContext<{ queryClient: QueryClient }>()({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { name: "google-site-verification", content: "A01V3-IeHdvZeFDITROkW10YpnYkVN54hH0CMBbKU6" },
      { title: "ChimCrew — Ohio Chimney Sweep & Repair" },
      { name: "description", content: "Locally owned Ohio chimney sweeps. CSIA-certified, flat-rate pricing, same-day callbacks." },
      { name: "author", content: "ChimCrew" },
      { property: "og:title", content: "ChimCrew — Ohio Chimney Sweep & Repair" },
      { property: "og:description", content: "Locally owned Ohio chimney sweeps. CSIA-certified, flat-rate pricing, same-day callbacks." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "twitter:title", content: "ChimCrew — Ohio Chimney Sweep & Repair" },
      { name: "twitter:description", content: "Locally owned Ohio chimney sweeps. CSIA-certified, flat-rate pricing, same-day callbacks." },
      { property: "og:image", content: "https://chimcrew.com/og-cover.jpg" },
      { name: "twitter:image", content: "https://chimcrew.com/og-cover.jpg" },
      { property: "og:site_name", content: "ChimCrew" },
    ],
    links: [
      /*
       * Fonts are self-hosted (public/fonts, generated by scripts/fetch-fonts.mjs)
       * and their @font-face rules are bundled into appCss. That removes the
       * render-blocking cross-origin stylesheet at fonts.googleapis.com and the
       * two preconnects it needed: first paint no longer waits on a DNS + TLS +
       * round trip just to learn the fonts.gstatic.com URLs, then a second
       * connection to fetch them.
       *
       * Same families, same weights, same `display=swap` — rendered typography
       * is unchanged. The set is still the trimmed one: Inter was dropped
       * earlier because it only ever sat behind Manrope/Geist in the --font-*
       * stacks, and Geist is narrowed to the 500/600/700/800 that
       * ServiceAreaMap paints its SVG labels in.
       *
       * Only the two faces that paint above the fold are preloaded — Manrope
       * 700 (the h1 and section headings) and Manrope 400 (hero body copy).
       * The rest are discovered from the stylesheet as before; preloading them
       * too would just contend with the LCP image.
       */
      {
        rel: "preload",
        as: "font",
        type: "font/woff2",
        href: "/fonts/manrope-700-normal-latin.woff2",
        crossOrigin: "anonymous",
      },
      {
        rel: "preload",
        as: "font",
        type: "font/woff2",
        href: "/fonts/manrope-400-normal-latin.woff2",
        crossOrigin: "anonymous",
      },
      {
        rel: "stylesheet",
        href: appCss,
      },
      {
        rel: "icon",
        href: "/favicon.ico",
        sizes: "any",
      },
      {
        rel: "icon",
        type: "image/png",
        sizes: "32x32",
        href: "/favicon-32x32.png",
      },
      {
        rel: "icon",
        type: "image/png",
        sizes: "16x16",
        href: "/favicon-16x16.png",
      },
      {
        rel: "icon",
        type: "image/png",
        sizes: "192x192",
        href: "/icon-192.png",
      },
      {
        rel: "icon",
        type: "image/png",
        sizes: "512x512",
        href: "/icon-512.png",
      },
      {
        rel: "apple-touch-icon",
        sizes: "180x180",
        href: "/apple-touch-icon.png",
      },
    ],
    scripts: [
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "LocalBusiness",
          "@id": "https://chimcrew.com/#business",
          name: "ChimCrew",
          description:
            "Locally owned chimney sweep, repair, and inspection company serving Columbus, Cincinnati, and Dayton, Ohio. CSIA-certified technicians.",
          url: "https://chimcrew.com",
          telephone: "+1-614-683-5763",
          priceRange: "$$",
          image: "https://chimcrew.com/og-cover.jpg",
          address: {
            "@type": "PostalAddress",
            addressLocality: "Columbus",
            addressRegion: "OH",
            addressCountry: "US",
          },
          areaServed: [
            { "@type": "City", name: "Columbus" },
            { "@type": "City", name: "Cincinnati" },
            { "@type": "City", name: "Dayton" },
            { "@type": "City", name: "Cleveland" },
            { "@type": "City", name: "Dublin" },
            { "@type": "City", name: "Hilliard" },
            { "@type": "City", name: "Westerville" },
            { "@type": "City", name: "Powell" },
            { "@type": "City", name: "Grove City" },
            { "@type": "City", name: "Worthington" },
          ],
          openingHoursSpecification: [
            {
              "@type": "OpeningHoursSpecification",
              dayOfWeek: ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday"],
              opens: "08:00",
              closes: "18:00",
            },
          ],
          sameAs: ["https://chimcrew.com"],
        }),
      },
    ],
  }),
  shellComponent: RootShell,
  component: RootComponent,
  notFoundComponent: NotFoundComponent,
  errorComponent: ErrorComponent,
});

function RootShell({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/*
          HeadContent first: it emits the charset/viewport meta, the font
          preconnects, the Google Fonts + app stylesheets and React's image
          preloads. Emitting it ahead of the third-party tags lets the preload
          scanner start those requests immediately instead of after the
          analytics block. No tag/config below is changed, only its position.
        */}
        <HeadContent />
        {/*
          GA4 + Google Ads.

          `dataLayer` and the three `gtag_report_*` helpers are installed
          synchronously here, so nothing that fires early is lost. Only the
          gtag.js download is deferred to first interaction / idle, and the two
          gtag.js tags are collapsed into one — gtag.js replays the queued
          `config`/`event` commands on arrival, and any conversion helper
          force-loads it immediately. See src/lib/tracking-bootstrap.ts for the
          full rationale; both IDs and the conversion label are unchanged.
        */}
        <script dangerouslySetInnerHTML={{ __html: TRACKING_BOOTSTRAP }} />
        {/*
          Hotjar — the stock async loader, unchanged (site 6728722, sv=6). It
          is deliberately NOT interaction- or idle-gated: Hotjar has no
          pre-load event queue we can rely on, and delaying it would start
          session recordings late.
        */}
        <script dangerouslySetInnerHTML={{ __html: HOTJAR_BOOTSTRAP }} />
        {/*
          buzzfufighter / ClickTrue — same URL and same `ct_clicktrue` class,
          loaded async from <head> exactly as before. Same reasoning as Hotjar:
          no proven pre-load queue, so its startup semantics stay untouched.
          Its noscript iframe is unchanged in <body> below.
        */}
        <script async src="https://ob.buzzfufighter.com/i/ecc955025644afe9ccafc17374332bd9.js" className="ct_clicktrue"></script>
        {/*
          CallRail swap.js — same account/company script, now `defer` so it no
          longer blocks the HTML parser (~1.2s on the live trace). It still runs
          before DOMContentLoaded, so number swapping and call tracking are
          unaffected.
        */}
        <script defer type="text/javascript" src="https://cdn.callrail.com/companies/575995871/0fa6a86aa27bec0d3aee/12/swap.js"></script>
      </head>
      <body>
        <noscript>
          <iframe
            src="https://ob.buzzfufighter.com/ns/ecc955025644afe9ccafc17374332bd9.html?ch="
            width="0"
            height="0"
            style={{ display: "none" }}
          />
        </noscript>
        <form
          name="chimcrew-lead"
          method="POST"
          data-netlify="true"
          data-netlify-honeypot="bot-field"
          hidden
          aria-hidden="true"
          tabIndex={-1}
        >
          <input type="hidden" name="form-name" value="chimcrew-lead" />
          <input name="bot-field" />
          <input name="name" />
          <input name="phone" />
          <input type="email" name="email" />
          <input name="service" />
          <input name="city" />
          <input name="address" />
          <input name="date" />
          <input name="timeWindow" />
          <textarea name="notes" />
          <input name="source" />
          <input name="smsConsent" />
        </form>
        {children}
        <Scripts />
      </body>
    </html>
  );
}

function RootComponent() {
  const { queryClient } = Route.useRouteContext();
  const pathname = useRouterState({ select: (s) => s.location.pathname });
  // Dedicated landing pages (/lp/*) render their own header/footer/CTAs.
  // Hide the main site chrome so paid traffic has zero exit links.
  const isLanding = pathname.startsWith("/lp/");

  // Track every click-to-call as a Google Ads conversion.
  // Without this, phone-call campaigns appear to deliver 0 leads
  // even when calls are actually happening.
  useEffect(() => {
    const onClick = (e: MouseEvent) => {
      const t = e.target as HTMLElement | null;
      const a = t?.closest?.("a[href^='tel:']") as HTMLAnchorElement | null;
      if (a) reportCallConversion();
    };
    document.addEventListener("click", onClick, { capture: true });
    return () => document.removeEventListener("click", onClick, { capture: true });
  }, []);

  return (
    <QueryClientProvider client={queryClient}>
      <div className="flex min-h-screen flex-col overflow-x-clip">
        {!isLanding && <SiteHeader />}
        <main className="flex-1">
          <Outlet />
        </main>
        {!isLanding && <SiteFooter />}
        {!isLanding && <StickyMobileCta />}
        <Toaster />
      </div>
    </QueryClientProvider>
  );
}
