#!/usr/bin/env node
/**
 * fetch-fonts.mjs
 *
 * Downloads the exact font files the site used to pull from Google Fonts and
 * writes them into `public/fonts`, plus a `src/fonts.css` with matching
 * `@font-face` rules pointed at the local copies.
 *
 * Why self-host: `<link rel="stylesheet" href="fonts.googleapis.com/css2?…">`
 * is render-blocking *and* cross-origin, so first paint had to wait on a DNS +
 * TLS + round trip to fonts.googleapis.com before it even learned the
 * fonts.gstatic.com URLs — a second connection and a second round trip. Serving
 * the same woff2 bytes from our own origin collapses that to zero extra
 * connections, and lets the above-fold faces be preloaded.
 *
 * The families, weights and `display=swap` are copied verbatim from the
 * previous <link>, so rendered typography is unchanged.
 *
 * Only `latin` and `latin-ext` subsets are kept. Google's CSS also lists
 * cyrillic/greek/vietnamese faces; `unicode-range` means a browser never
 * downloaded those for this site's content, so they are dead weight in the
 * repo.
 *
 * Usage:  node scripts/fetch-fonts.mjs
 * Re-run only when the font list changes.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const GOOGLE_CSS_URL =
  "https://fonts.googleapis.com/css2?family=Archivo+Black&family=Bungee&family=Geist:wght@500;600;700;800&family=JetBrains+Mono:wght@400;500;700&family=Manrope:wght@400;500;600;700;800&family=Oswald:wght@400;500;600;700&display=swap";

// A modern desktop UA makes Google serve woff2 (the smallest format all our
// supported browsers understand) rather than ttf.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

const ROOT = path.resolve(import.meta.dirname, "..");
const FONT_DIR = path.join(ROOT, "public", "fonts");
const CSS_OUT = path.join(ROOT, "src", "fonts.css");

const css = await fetch(GOOGLE_CSS_URL, { headers: { "user-agent": UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts CSS ${r.status}`);
  return r.text();
});

await mkdir(FONT_DIR, { recursive: true });

// Google's CSS is a flat list of `/* subset */ @font-face { … }` blocks.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
if (!blocks.length) throw new Error("Could not parse any @font-face blocks");

const out = [];
const seen = new Set();
let downloaded = 0;
let bytes = 0;

for (const [, subset, block] of blocks) {
  if (!KEEP_SUBSETS.has(subset)) continue;

  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? "400";
  const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? "normal";
  const url = /src:\s*url\((https:[^)]+)\)/.exec(block)?.[1];
  const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1];
  if (!family || !url) continue;

  const slug = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}-${style}-${subset}.woff2`;
  if (!seen.has(slug)) {
    seen.add(slug);
    const buf = Buffer.from(
      await fetch(url, { headers: { "user-agent": UA } }).then((r) => {
        if (!r.ok) throw new Error(`font ${slug} -> ${r.status}`);
        return r.arrayBuffer();
      }),
    );
    await writeFile(path.join(FONT_DIR, slug), buf);
    downloaded++;
    bytes += buf.length;
    console.log(`  ${slug}  ${(buf.length / 1024).toFixed(1)} KB`);
  }

  out.push(
    [
      `@font-face {`,
      `  font-family: '${family}';`,
      `  font-style: ${style};`,
      `  font-weight: ${weight};`,
      `  font-display: swap;`,
      `  src: url('/fonts/${slug}') format('woff2');`,
      range ? `  unicode-range: ${range};` : null,
      `}`,
    ]
      .filter(Boolean)
      .join("\n"),
  );
}

const header = `/*
 * GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
 *
 * Self-hosted copies of the exact Google Fonts faces the site used to load from
 * fonts.googleapis.com. Same families, same weights, same font-display: swap,
 * so rendered typography is identical; the cross-origin render-blocking
 * stylesheet and its extra connection are gone.
 */\n`;

await writeFile(CSS_OUT, header + out.join("\n\n") + "\n");

console.log(
  `\n${downloaded} files, ${(bytes / 1024).toFixed(0)} KB total -> public/fonts` +
    `\n${out.length} @font-face rules -> src/fonts.css`,
);
