/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeforeAfterRouteImport } from './routes/before-after'
import { Route as ChimneyRepairColumbusRouteImport } from './routes/chimney-repair-columbus'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AdminEstimatesRouteImport } from './routes/admin.estimates'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ChimneyRepairCityRouteImport } from './routes/chimney-repair.$city'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LegalAccessibilityRouteImport } from './routes/legal/accessibility'
import { Route as LegalDisclaimerRouteImport } from './routes/legal/disclaimer'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LpFreeInspectionRouteImport } from './routes/lp.free-inspection'
import { Route as ServiceAreaCityRouteImport } from './routes/service-area.$city'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ApiPublicNotifyLeadRouteImport } from './routes/api/public/notify-lead'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeforeAfterRoute = BeforeAfterRouteImport.update({
  id: '/before-after',
  path: '/before-after',
  getParentRoute: () => rootRouteImport,
} as any)
const ChimneyRepairColumbusRoute = ChimneyRepairColumbusRouteImport.update({
  id: '/chimney-repair-columbus',
  path: '/chimney-repair-columbus',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEstimatesRoute = AdminEstimatesRouteImport.update({
  id: '/admin/estimates',
  path: '/admin/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChimneyRepairCityRoute = ChimneyRepairCityRouteImport.update({
  id: '/chimney-repair/$city',
  path: '/chimney-repair/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAccessibilityRoute = LegalAccessibilityRouteImport.update({
  id: '/legal/accessibility',
  path: '/legal/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LpFreeInspectionRoute = LpFreeInspectionRouteImport.update({
  id: '/lp/free-inspection',
  path: '/lp/free-inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaCityRoute = ServiceAreaCityRouteImport.update({
  id: '/service-area/$city',
  path: '/service-area/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyLeadRoute = ApiPublicNotifyLeadRouteImport.update({
  id: '/api/public/notify-lead',
  path: '/api/public/notify-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/before-after': typeof BeforeAfterRoute
  '/chimney-repair-columbus': typeof ChimneyRepairColumbusRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/estimates': typeof AdminEstimatesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/chimney-repair/$city': typeof ChimneyRepairCityRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/lp/free-inspection': typeof LpFreeInspectionRoute
  '/service-area/$city': typeof ServiceAreaCityRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/public/notify-lead': typeof ApiPublicNotifyLeadRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/before-after': typeof BeforeAfterRoute
  '/chimney-repair-columbus': typeof ChimneyRepairColumbusRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/estimates': typeof AdminEstimatesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/chimney-repair/$city': typeof ChimneyRepairCityRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/lp/free-inspection': typeof LpFreeInspectionRoute
  '/service-area/$city': typeof ServiceAreaCityRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/public/notify-lead': typeof ApiPublicNotifyLeadRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/before-after': typeof BeforeAfterRoute
  '/chimney-repair-columbus': typeof ChimneyRepairColumbusRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/estimates': typeof AdminEstimatesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/chimney-repair/$city': typeof ChimneyRepairCityRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/lp/free-inspection': typeof LpFreeInspectionRoute
  '/service-area/$city': typeof ServiceAreaCityRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/public/notify-lead': typeof ApiPublicNotifyLeadRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/before-after'
    | '/chimney-repair-columbus'
    | '/contact'
    | '/financing'
    | '/gallery'
    | '/reviews'
    | '/schedule'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/estimates'
    | '/admin/leads'
    | '/blog/$slug'
    | '/chimney-repair/$city'
    | '/email/unsubscribe'
    | '/legal/accessibility'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/lp/free-inspection'
    | '/service-area/$city'
    | '/services/$slug'
    | '/blog/'
    | '/services/'
    | '/api/public/notify-lead'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/before-after'
    | '/chimney-repair-columbus'
    | '/contact'
    | '/financing'
    | '/gallery'
    | '/reviews'
    | '/schedule'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/estimates'
    | '/admin/leads'
    | '/blog/$slug'
    | '/chimney-repair/$city'
    | '/email/unsubscribe'
    | '/legal/accessibility'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/lp/free-inspection'
    | '/service-area/$city'
    | '/services/$slug'
    | '/blog'
    | '/services'
    | '/api/public/notify-lead'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/before-after'
    | '/chimney-repair-columbus'
    | '/contact'
    | '/financing'
    | '/gallery'
    | '/reviews'
    | '/schedule'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/estimates'
    | '/admin/leads'
    | '/blog/$slug'
    | '/chimney-repair/$city'
    | '/email/unsubscribe'
    | '/legal/accessibility'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/lp/free-inspection'
    | '/service-area/$city'
    | '/services/$slug'
    | '/blog/'
    | '/services/'
    | '/api/public/notify-lead'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeforeAfterRoute: typeof BeforeAfterRoute
  ChimneyRepairColumbusRoute: typeof ChimneyRepairColumbusRoute
  ContactRoute: typeof ContactRoute
  FinancingRoute: typeof FinancingRoute
  GalleryRoute: typeof GalleryRoute
  ReviewsRoute: typeof ReviewsRoute
  ScheduleRoute: typeof ScheduleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminEstimatesRoute: typeof AdminEstimatesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ChimneyRepairCityRoute: typeof ChimneyRepairCityRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LegalAccessibilityRoute: typeof LegalAccessibilityRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LpFreeInspectionRoute: typeof LpFreeInspectionRoute
  ServiceAreaCityRoute: typeof ServiceAreaCityRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiPublicNotifyLeadRoute: typeof ApiPublicNotifyLeadRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/before-after': {
      id: '/before-after'
      path: '/before-after'
      fullPath: '/before-after'
      preLoaderRoute: typeof BeforeAfterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chimney-repair-columbus': {
      id: '/chimney-repair-columbus'
      path: '/chimney-repair-columbus'
      fullPath: '/chimney-repair-columbus'
      preLoaderRoute: typeof ChimneyRepairColumbusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/estimates': {
      id: '/admin/estimates'
      path: '/admin/estimates'
      fullPath: '/admin/estimates'
      preLoaderRoute: typeof AdminEstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chimney-repair/$city': {
      id: '/chimney-repair/$city'
      path: '/chimney-repair/$city'
      fullPath: '/chimney-repair/$city'
      preLoaderRoute: typeof ChimneyRepairCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/accessibility': {
      id: '/legal/accessibility'
      path: '/legal/accessibility'
      fullPath: '/legal/accessibility'
      preLoaderRoute: typeof LegalAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/free-inspection': {
      id: '/lp/free-inspection'
      path: '/lp/free-inspection'
      fullPath: '/lp/free-inspection'
      preLoaderRoute: typeof LpFreeInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area/$city': {
      id: '/service-area/$city'
      path: '/service-area/$city'
      fullPath: '/service-area/$city'
      preLoaderRoute: typeof ServiceAreaCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-lead': {
      id: '/api/public/notify-lead'
      path: '/api/public/notify-lead'
      fullPath: '/api/public/notify-lead'
      preLoaderRoute: typeof ApiPublicNotifyLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeforeAfterRoute: BeforeAfterRoute,
  ChimneyRepairColumbusRoute: ChimneyRepairColumbusRoute,
  ContactRoute: ContactRoute,
  FinancingRoute: FinancingRoute,
  GalleryRoute: GalleryRoute,
  ReviewsRoute: ReviewsRoute,
  ScheduleRoute: ScheduleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminEstimatesRoute: AdminEstimatesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ChimneyRepairCityRoute: ChimneyRepairCityRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LegalAccessibilityRoute: LegalAccessibilityRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LpFreeInspectionRoute: LpFreeInspectionRoute,
  ServiceAreaCityRoute: ServiceAreaCityRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiPublicNotifyLeadRoute: ApiPublicNotifyLeadRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
