// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'

/**
 * Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
 * the browser never attaches the bearer token to serverFn RPCs.
 *
 * `./client` is pulled in with a dynamic import rather than a static one. As a
 * static import it was reachable from the client entry, so `@supabase/supabase-js`
 * and its auth/realtime/postgrest/storage sub-packages (~700 KB of rendered
 * module source) were bundled into the shared entry chunk and parsed on every
 * page — including the marketing pages, none of which talk to Supabase.
 *
 * Only serverFn RPCs run this middleware, and those live on the admin routes, so
 * the client is now fetched on first RPC instead of on first paint. The
 * middleware body was already async and already awaited the session before
 * calling `next()`, so the token is attached exactly as before.
 */
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { supabase } = await import('./client')
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
